apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nacos-mysql
  namespace: nacos
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
